### ISSUE TITLE
A question about the model

### ISSUE THREAD

**Issue by Ecalpal** [mengcius/Surface-Defect-Detection#1]
An error occurred when I was running `python models.py`

python models.py 
Traceback (most recent call last):
  File "models.py", line 163, in <module>
    ret = snet(img)
  File "/home/A305/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "models.py", line 87, in forward
    w = F.avg_pool2d(x3, x3.size(2))
RuntimeError: Given input size: (64x88x32). Calculated output size: (64x1x0). Output size is too small

Is there any way to fix it?

Ubuntu version: 20.04
Pytorch version: 1.7
CUDA version: 11.0

**Comment by Yangly0** [comment]
`
w = F.avg_pool2d(x3, (x3.size(2), x3.size(3)))  # by yr
`

**Comment by LeBron-Jian** [comment]
> `w = F.avg_pool2d(x3, (x3.size(2), x3.size(3))) # by yr`


Tks
