### ISSUE TITLE
why not use decision_net.eval()?

### ISSUE THREAD

**Issue by LeBron-Jian** [mengcius/Surface-Defect-Detection#2]
segment_net.eval()
# decision_net.eval()

hi:
      tks for you job, I have a question
I opened the comment and it didn't work very well in test.py, but I didn't understand why.Please give advice or comments

**Comment by BonaDebela** [comment]
> segment_net.eval()
> 
> # decision_net.eval()
> hi:
> tks for you job, I have a question
> I opened the comment and it didn't work very well in test.py, but I didn't understand why.Please give advice or comments

@LeBron-Jian the accuracy I got after testing is around 50%.  what about you? please reply me back.

**Comment by LeBron-Jian** [comment]
> > segment_net.eval()
> > # decision_net.eval()
> > hi:
> > tks for you job, I have a question
> > I opened the comment and it didn't work very well in test.py, but I didn't understand why.Please give advice or comments
> 
> @LeBron-Jian the accuracy I got after testing is around 50%. what about you? please reply me back.

the accuracy of my code is around 99%

**Comment by BonaDebela** [comment]
> > > segment_net.eval()
> > > # decision_net.eval()
> > > hi:
> > > tks for you job, I have a question
> > > I opened the comment and it didn't work very well in test.py, but I didn't understand why.Please give advice or comments
> > 
> > 
> > @LeBron-Jian the accuracy I got after testing is around 50%. what about you? please reply me back.
> 
> the accuracy of my code is around 99%

thanks.
